export interface User{
    uiNum?:number;
    uiId?:string;
    uiPwd?:string;
    uiName?:string;
    uiEmail?:string;
    uiPhone?:string;
    uiBirth?:string;
    uiGender?:string;
    uiGrade?:string;
    uiCredat?:string;
    uiCretim?:string;
    uiLmodat?:string;
    uiLmotim?:string;
    riNum?:number;
    token?:string;
    uiImgPath?:string;
    login?:boolean;
    authorities?:any[];
}